// @flow

export const TEAM_REQUEST: string = 'admin.signin/TEAM_REQUEST'
export const TEAM_SUCCESS: string = 'admin.signin/TEAM_SUCCESS'
export const TEAM_FAILURE: string = 'admin.signin/TEAM_FAILURE'
export const EMAIL_REQUEST: string = 'admin.signin/EMAIL_REQUEST'
export const EMAIL_SUCCESS: string = 'admin.signin/EMAIL_SUCCESS'
export const EMAIL_FAILURE: string = 'admin.signin/EMAIL_FAILURE'
export const TOGGLE_PASSWORD: string = 'admin.signin/TOGGLE_PASSWORD'
export const PASSWORD_REQUEST: string = 'admin.signin/PASSWORD_REQUEST'
export const PASSWORD_SUCCESS: string = 'admin.signin/PASSWORD_SUCCESS'
export const PASSWORD_FAILURE: string = 'admin.signin/PASSWORD_FAILURE'
export const FORGOT_REQUEST: string = 'admin.signin/FORGOT_REQUEST'
export const FORGOT_SUCCESS: string = 'admin.signin/FORGOT_SUCCESS'
export const FORGOT_FAILURE: string = 'admin.signin/FORGOT_FAILURE'
export const RESET: string = 'admin.signin/RESET'
