exports.seed = (knex, Promise) => {
  return knex('teams').del()
  .then(() => {
    return knex('teams').insert([
      {
        title: 'Cornell Cooperative Extension of Tompkins County',
        subdomain: 'ccetc'
      }, {
        title: 'Think Topography',
        subdomain: 'thinktopography'
      }
    ])
  })
  .then(() => {
    return knex('app_authors').del()
  })
  .then(() => {
    return knex('app_authors').insert([
      {
        name: 'CCE Tompkins'
      }, {
        name: 'Think Topography'
      }
    ])
  })
  .then(() => {
    return knex('apps').del()
  })
  .then(() => {
    return knex('apps').insert([
      {
        title: 'Team',
        app_category_id: 1,
        app_author_id: 1,
        short_description: 'Manage team settings, users, apps, access, and activity',
        long_description: 'Vexillologist viral stumptown salvia. Asymmetrical green juice lumbersexual, microdosing hell of yuccie messenger bag butcher pok pok XOXO organic neutra brunch bushwick street art. Meh iceland disrupt, polaroid skateboard lo-fi chambray tofu tumblr green juice vexillologist cliche umami. Wolf put a bird on it gochujang health goth, gluten-free synth cliche pork belly succulents unicorn selfies kinfolk tofu. Vexillologist viral stumptown salvia. Asymmetrical green juice lumbersexual, microdosing hell of yuccie messenger bag butcher pok pok XOXO organic neutra brunch bushwick street art. Meh iceland disrupt, polaroid skateboard lo-fi chambray tofu tumblr green juice vexillologist cliche umami. Wolf put a bird on it gochujang health goth, gluten-free synth cliche pork belly succulents unicorn selfies kinfolk tofu.',
        version: '1.0.0',
        icon: 'users'
      }, {
        title: 'Expenses',
        app_category_id: 4,
        app_author_id: 1,
        short_description: 'Manage expenses for expenses, advances, and vehicle trips',
        long_description: 'Vexillologist viral stumptown salvia. Asymmetrical green juice lumbersexual, microdosing hell of yuccie messenger bag butcher pok pok XOXO organic neutra brunch bushwick street art. Meh iceland disrupt, polaroid skateboard lo-fi chambray tofu tumblr green juice vexillologist cliche umami. Wolf put a bird on it gochujang health goth, gluten-free synth cliche pork belly succulents unicorn selfies kinfolk tofu. Vexillologist viral stumptown salvia. Asymmetrical green juice lumbersexual, microdosing hell of yuccie messenger bag butcher pok pok XOXO organic neutra brunch bushwick street art. Meh iceland disrupt, polaroid skateboard lo-fi chambray tofu tumblr green juice vexillologist cliche umami. Wolf put a bird on it gochujang health goth, gluten-free synth cliche pork belly succulents unicorn selfies kinfolk tofu.',
        version: '1.0.0',
        icon: 'dollar'
      }, {
        title: 'Competency',
        app_category_id: 3,
        app_author_id: 1,
        short_description: 'Vexillologist viral stumptown salvia. Asymmetrical green juice lumbersexual.',
        long_description: 'Vexillologist viral stumptown salvia. Asymmetrical green juice lumbersexual, microdosing hell of yuccie messenger bag butcher pok pok XOXO organic neutra brunch bushwick street art. Meh iceland disrupt, polaroid skateboard lo-fi chambray tofu tumblr green juice vexillologist cliche umami. Wolf put a bird on it gochujang health goth, gluten-free synth cliche pork belly succulents unicorn selfies kinfolk tofu. Vexillologist viral stumptown salvia. Asymmetrical green juice lumbersexual, microdosing hell of yuccie messenger bag butcher pok pok XOXO organic neutra brunch bushwick street art. Meh iceland disrupt, polaroid skateboard lo-fi chambray tofu tumblr green juice vexillologist cliche umami. Wolf put a bird on it gochujang health goth, gluten-free synth cliche pork belly succulents unicorn selfies kinfolk tofu.',
        version: '1.0.0',
        icon: 'trophy'
      }, {
        title: 'Learning',
        app_category_id: 3,
        app_author_id: 1,
        short_description: 'Vexillologist viral stumptown salvia. Asymmetrical green juice lumbersexual.',
        long_description: 'Vexillologist viral stumptown salvia. Asymmetrical green juice lumbersexual, microdosing hell of yuccie messenger bag butcher pok pok XOXO organic neutra brunch bushwick street art. Meh iceland disrupt, polaroid skateboard lo-fi chambray tofu tumblr green juice vexillologist cliche umami. Wolf put a bird on it gochujang health goth, gluten-free synth cliche pork belly succulents unicorn selfies kinfolk tofu. Vexillologist viral stumptown salvia. Asymmetrical green juice lumbersexual, microdosing hell of yuccie messenger bag butcher pok pok XOXO organic neutra brunch bushwick street art. Meh iceland disrupt, polaroid skateboard lo-fi chambray tofu tumblr green juice vexillologist cliche umami. Wolf put a bird on it gochujang health goth, gluten-free synth cliche pork belly succulents unicorn selfies kinfolk tofu.',
        version: '1.0.0',
        icon: 'book'
      }, {
        title: 'Website',
        app_category_id: 3,
        app_author_id: 2,
        short_description: 'Vexillologist viral stumptown salvia. Asymmetrical green juice lumbersexual.',
        long_description: 'Vexillologist viral stumptown salvia. Asymmetrical green juice lumbersexual, microdosing hell of yuccie messenger bag butcher pok pok XOXO organic neutra brunch bushwick street art. Meh iceland disrupt, polaroid skateboard lo-fi chambray tofu tumblr green juice vexillologist cliche umami. Wolf put a bird on it gochujang health goth, gluten-free synth cliche pork belly succulents unicorn selfies kinfolk tofu. Vexillologist viral stumptown salvia. Asymmetrical green juice lumbersexual, microdosing hell of yuccie messenger bag butcher pok pok XOXO organic neutra brunch bushwick street art. Meh iceland disrupt, polaroid skateboard lo-fi chambray tofu tumblr green juice vexillologist cliche umami. Wolf put a bird on it gochujang health goth, gluten-free synth cliche pork belly succulents unicorn selfies kinfolk tofu.',
        version: '1.0.0',
        icon: 'globe'
      }
    ])
  })
  .then(() => {
    return knex('rights').del()
  })
  .then(() => {
    return knex('rights').insert([
      {
        app_id: 1,
        text: 'ADMIN TEAM',
        description: 'user can manage team settings'
      }, {
        app_id: 2,
        text: 'MANAGE EXPENSES',
        description: 'user can manage their own advances, expenses, and trips'
      }, {
        app_id: 2,
        text: 'SUPERVISE EXPENSES',
        description: 'user can access all advances, expense, and trip reports'
      }, {
        app_id: 2,
        text: 'ADMIN EXPENSES',
        description: 'user can manage projects, vendors, and expense types'
      }
    ])
  })
  .then(() => {
    return knex('installations').del()
  })
  .then(() => {
    return knex('installations').insert([
      {
        team_id: 1,
        app_id: 1
      }, {
        team_id: 1,
        app_id: 2
      }, {
        team_id: 2,
        app_id: 2
      }
    ])
  })
  .then(() => {
    return knex('strategies').del()
  })
  .then(() => {
    return knex('strategies').insert([
      {
        team_id: 1,
        name: 'cornell'
      }, {
        team_id: 2,
        name: 'google'
      }
    ])
  })
  .then(() => {
    return knex('assets').del()
  })
  .then(() => {
    return knex('assets').insert([
      {
        team_id: 1,
        original_file_name: 'ken.jpg',
        file_name: 'ken.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'sharon.jpg',
        file_name: 'sharon.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'sandy.jpg',
        file_name: 'sandy.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'greg.jpg',
        file_name: 'greg.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'sharon-anderson150x150.jpg',
        file_name: 'sharon-anderson150x150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'beth-bannister150.jpg',
        file_name: 'beth-bannister150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'karim-beers150.jpg',
        file_name: 'karim-beers150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'jim-blizzard150.jpg',
        file_name: 'jim-blizzard150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'maria-christian150.jpg',
        file_name: 'maria-christian150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'tim-crowley150.jpg',
        file_name: 'tim-crowley150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'pat-curran150.jpg',
        file_name: 'pat-curran150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'theresa-emerick150.jpg',
        file_name: 'theresa-emerick150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'jennifer-grey150.jpg',
        file_name: 'jennifer-grey150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'vendamae-harris150.jpg',
        file_name: 'vendamae-harris150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'kathy-jett150.jpg',
        file_name: 'kathy-jett150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'lara-kaltman150sq.jpg',
        file_name: 'lara-kaltman150sq.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'matt-leroux-professional.jpg',
        file_name: 'matt-leroux-professional.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'kathy-maxson150.jpg',
        file_name: 'kathy-maxson150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'guillermo-metz.jpg',
        file_name: 'guillermo-metz.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'adam-michaelides150.jpg',
        file_name: 'adam-michaelides150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'avi-miner150.jpg',
        file_name: 'avi-miner150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'sandy.jpg',
        file_name: 'sandy.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'Monika_Roth06.jpg',
        file_name: 'Monika_Roth06.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'ken-schlather150.jpg',
        file_name: 'ken-schlather150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'tina-snyder_2-150.jpg',
        file_name: 'tina-snyder_2-150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'megan-tifft150.jpg',
        file_name: 'megan-tifft150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'heather-ward2-150.jpg',
        file_name: 'heather-ward2-150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'staff-debbie-teeter150jp.jpg',
        file_name: 'staff-debbie-teeter150jp.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'chrys-gardener2-150x150.jpg',
        file_name: 'chrys-gardener2-150x150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'liz-karabinakis2-150.jpg',
        file_name: 'liz-karabinakis2-150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'brenda-carpenter150.jpg',
        file_name: 'brenda-carpenter150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'leigh-macdonald-rizzo_2_150.jpg',
        file_name: 'leigh-macdonald-rizzo_2_150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'erin-marteal150.jpg',
        file_name: 'erin-marteal150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'fabina-colon2-150.jpg',
        file_name: 'fabina-colon2-150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'nikki-neese150.jpg',
        file_name: 'nikki-neese150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'lauren-salzman150.jpg',
        file_name: 'lauren-salzman150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'ramona-cornell-150.jpg',
        file_name: 'ramona-cornell-150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'amanda-david150.jpg',
        file_name: 'amanda-david150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'josh-dolan150.jpg',
        file_name: 'josh-dolan150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'chrisophia-somerfeldt150.jpg',
        file_name: 'chrisophia-somerfeldt150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'anna-steinkraus150.jpg',
        file_name: 'anna-steinkraus150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'monica-dykeman-150.jpg',
        file_name: 'monica-dykeman-150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'justin-sutera.jpg',
        file_name: 'justin-sutera.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'corinne-eisenman150.jpg',
        file_name: 'corinne-eisenman150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'jeanne-freese-popowitch150.jpg',
        file_name: 'jeanne-freese-popowitch150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'elizabeth-wolff150.jpg',
        file_name: 'elizabeth-wolff150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'martha-gioumousis150.jpg',
        file_name: 'martha-gioumousis150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'staff-krystal-dunn150.jpg',
        file_name: 'staff-krystal-dunn150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'pat-haggerty150.jpg',
        file_name: 'pat-haggerty150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'joann-huddle150.jpg',
        file_name: 'joann-huddle150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'Holly_Gump2-_5x7t.jpg',
        file_name: 'Holly_Gump2-_5x7t.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'meagn-pugh150.jpg',
        file_name: 'meagn-pugh150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'Norma_Gutierrez2-150.jpg',
        file_name: 'Norma_Gutierrez2-150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'barb-sinn150.jpg',
        file_name: 'barb-sinn150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'dave-hall150.jpg',
        file_name: 'dave-hall150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'Margo300px.jpg',
        file_name: 'Margo300px.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'jed_jordan_150px.jpg',
        file_name: 'jed_jordan_150px.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'janis-degni.jpg',
        file_name: 'janis-degni.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'a-fay-benson2.jpg',
        file_name: 'a-fay-benson2.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'Heather_1_.png',
        file_name: 'Heather_1_.png',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'brett-chedzoy.jpg',
        file_name: 'brett-chedzoy.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'shelley-lester2-150.jpg',
        file_name: 'shelley-lester2-150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'marjorie-olds150.jpg',
        file_name: 'marjorie-olds150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'Min_Liu_150.jpg',
        file_name: 'Min_Liu_150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'Athena_Steinkraus_150.jpg',
        file_name: 'Athena_Steinkraus_150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'sarah-brown150.jpg',
        file_name: 'sarah-brown150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'john-chilkotowsky150.jpg',
        file_name: 'john-chilkotowsky150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'betsy-hicks.jpg',
        file_name: 'betsy-hicks.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'lisa-ellin-2-150.jpg',
        file_name: 'lisa-ellin-2-150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'sean-cornell150.jpg',
        file_name: 'sean-cornell150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'Travis_Judd_150x150.jpg',
        file_name: 'Travis_Judd_150x150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }
    ])
  })
  .then(() => {
    return knex('assets').insert([
      {
        team_id: 1,
        original_file_name: 'Ethan-Cramton.jpg',
        file_name: 'Ethan-Cramton.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'Aloja-Airwele.jpg',
        file_name: 'Aloja-Airwele.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'kenneth-mclaurin-150.jpg',
        file_name: 'kenneth-mclaurin-150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'hector-chang-150px.jpg',
        file_name: 'hector-chang-150px.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'Zack_Kozlowski_150.jpg',
        file_name: 'Zack_Kozlowski_150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'mark-andrew-barker150.jpg',
        file_name: 'mark-andrew-barker150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'Britton-Dougherty.jpg',
        file_name: 'Britton-Dougherty.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'chris-kai-jones3-150.jpg',
        file_name: 'chris-kai-jones3-150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'gibrian-hagood150.jpg',
        file_name: 'gibrian-hagood150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'hannah-kinsella150.jpg',
        file_name: 'hannah-kinsella150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'judy-burrill150x150.jpg',
        file_name: 'judy-burrill150x150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'Khulani-Mkhonza150px.jpg',
        file_name: 'Khulani-Mkhonza150px.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'PhoebeBrown300px.jpg',
        file_name: 'PhoebeBrown300px.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'deborah-campos150x150.jpg',
        file_name: 'deborah-campos150x150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'Nancy_Malina_150px.jpg',
        file_name: 'Nancy_Malina_150px.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'zoe-van-nostrand2.jpg',
        file_name: 'zoe-van-nostrand2.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'Terry_Carroll_150px.jpg',
        file_name: 'Terry_Carroll_150px.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'adam-flint.jpg',
        file_name: 'adam-flint.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'meagan-pulver150.jpg',
        file_name: 'meagan-pulver150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'Megan-Szpak_150.jpg',
        file_name: 'Megan-Szpak_150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'jack-davidson150x150.jpg',
        file_name: 'jack-davidson150x150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'eric-carter150x150.jpg',
        file_name: 'eric-carter150x150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'laura-komor150.jpg',
        file_name: 'laura-komor150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'michele-jones-1-150.jpg',
        file_name: 'michele-jones-1-150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'rebecca-9.jpg',
        file_name: 'rebecca-9.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'Kina_Viola_150.jpg',
        file_name: 'Kina_Viola_150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'Thena_LeVan_150x150.jpg',
        file_name: 'Thena_LeVan_150x150.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'blue-avatar.jpg',
        file_name: 'blue-avatar.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'pink-avatar.jpg',
        file_name: 'pink-avatar.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'pink-avatar.jpg',
        file_name: 'pink-avatar.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'blue-avatar.jpg',
        file_name: 'blue-avatar.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'annalise-kukor150sq.jpg',
        file_name: 'annalise-kukor150sq.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 1,
        original_file_name: 'cornell.png',
        file_name: 'cornell.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 2,
        original_file_name: 'think.jpg',
        file_name: 'think.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }, {
        team_id: 2,
        original_file_name: 'greg.jpg',
        file_name: 'greg.jpg',
        content_type: 'image/jpeg',
        file_size: 12345,
        fingerprint: 'aefasdf7dsaf6sd87sda6f'
      }
    ])
  })
  .then(() => {
    return knex('teams').where({
      id: 1
    }).update({
      logo_id: 104
    })
  })
  .then(() => {
    return knex('teams').where({
      id: 2
    }).update({
      logo_id: 105
    })
  })
  .then(() => {
    return knex('users').del()
  })
  .then(() => {
    return knex('users').insert([
      {
        team_id: 1,
        first_name: 'Greg',
        last_name: 'Kops',
        email: 'gmk8@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 4,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Sharon',
        last_name: 'Anderson',
        email: 'ska2@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 5,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Beth',
        last_name: 'Bannister',
        email: 'bab47@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 6,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Karim',
        last_name: 'Beers',
        email: 'kwb6@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 7,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Jim',
        last_name: 'Blizzard',
        email: 'jpb27@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 8,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Maria',
        last_name: 'Christian',
        email: 'mjc72@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 9,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Tim',
        last_name: 'Crowley',
        email: 'tfc43@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 10,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Patricia',
        last_name: 'Curran',
        email: 'pc21@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 11,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Theresa',
        last_name: 'Emerick',
        email: 'tee1@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 12,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Jennifer',
        last_name: 'Gray',
        email: 'jcg33@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 13,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Venda Mae',
        last_name: 'Harris',
        email: 'vmt5@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 14,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Kathy',
        last_name: 'Jett',
        email: 'klj27@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 15,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Lara Parrilla',
        last_name: 'Kaltman',
        email: 'ljp9@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 16,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Matthew',
        last_name: 'LeRoux',
        email: 'mnl28@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 17,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Kathy',
        last_name: 'Maxson',
        email: 'kmm242@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 18,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Guillermo',
        last_name: 'Metz',
        email: 'gm52@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 19,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Adam',
        last_name: 'Michaelides',
        email: 'acm1@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 20,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Avi',
        last_name: 'Miner',
        email: 'agm32@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 21,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Sandy',
        last_name: 'Repp',
        email: 'sjr37@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 22,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Monika',
        last_name: 'Roth',
        email: 'mr55@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 23,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Kenneth J.',
        last_name: 'Schlather',
        email: 'ks47@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 24,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Tina M.',
        last_name: 'Snyder',
        email: 'tmf8@cornell.edu ',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 25,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Megan',
        last_name: 'Tifft',
        email: 'met38@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 26,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Heather',
        last_name: 'Ward',
        email: 'hab27@cornell.edu ',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 27,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Debbie',
        last_name: 'Teeter',
        email: 'dlt22@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 28,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Chrys',
        last_name: 'Gardener',
        email: 'cab69@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 29,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Liz',
        last_name: 'Karabinakis',
        email: 'evk4@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 30,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Brenda T.',
        last_name: 'Carpenter',
        email: 'btc6@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 31,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Leigh',
        last_name: 'MacDonald-Rizzo',
        email: 'lam26@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 32,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Erin',
        last_name: 'Marteal',
        email: 'enm6@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 33,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Fabina',
        last_name: 'Colon',
        email: 'fabina@multiculturalresourcecenter.org',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 34,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Nikki',
        last_name: 'Nease',
        email: 'njn35@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 35,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Lauren',
        last_name: 'Salzman',
        email: 'las466@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 36,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Ramona',
        last_name: 'Cornell',
        email: 'rlc263@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 37,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Amanda',
        last_name: 'David',
        email: 'healthyfoodforall.ithaca@gmail.com',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 38,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Josh',
        last_name: 'Dolan',
        email: 'jd285@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 39,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Chrisophia',
        last_name: 'Somerfeldt',
        email: 'css17@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 40,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Anna',
        last_name: 'Steinkraus',
        email: 'ams69@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 41,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Monica',
        last_name: 'Dykeman',
        email: 'mmd1027@aol.com',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 42,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Justin',
        last_name: 'Sutera',
        email: '',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 43,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Corinne',
        last_name: 'Eisenman',
        email: 'cee29@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 44,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Jean L.',
        last_name: 'Freese-Popowitch',
        email: 'jlf30@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 45,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Elizabeth',
        last_name: 'Wolff',
        email: 'ebw52@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 46,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Martha',
        last_name: 'Gioumousis',
        email: 'mg10@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 47,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Krystal',
        last_name: 'Watson',
        email: 'krk7@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 48,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Pat',
        last_name: 'Haggerty',
        email: 'pmh75@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 49,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'JoAnn',
        last_name: 'Huddle',
        email: 'jmh37@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 50,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Holly',
        last_name: 'Gump',
        email: 'hmg2@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 51,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Megan',
        last_name: 'Pugh',
        email: 'meganmpugh@gmail.com',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 52,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Norma',
        last_name: 'Gutierrez',
        email: 'ng32@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 53,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Barbara',
        last_name: 'Sinn',
        email: 'bas25@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 54,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'David',
        last_name: 'Hall',
        email: 'dh67@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 55,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Margo',
        last_name: 'Hittleman',
        email: 'mjh17@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 56,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Jed',
        last_name: 'Jordan',
        email: 'jedjordan@hotmail.com',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 57,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Janice',
        last_name: 'Degni',
        email: 'jgd3@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 58,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'A. Fay',
        last_name: 'Benson',
        email: 'afb3@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 59,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Heather',
        last_name: 'Birdsall',
        email: 'hhb6@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 60,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Brett',
        last_name: 'Chedzoy',
        email: 'bjc226@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 61,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Shelley ',
        last_name: 'Lester',
        email: 'sjl44@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 62,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Marjorie',
        last_name: 'Olds',
        email: 'mzo2@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 63,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Min',
        last_name: 'Liu',
        email: 'ml989@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 64,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Athena',
        last_name: 'Steinkraus',
        email: 'ahs38@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 65,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Sarah',
        last_name: 'Brown',
        email: 'sb2275@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 66,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'John',
        last_name: 'Chilkotowsky',
        email: 'jc2889@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 67,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Betsy',
        last_name: 'Hicks',
        email: 'bjh246@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 68,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Lisa',
        last_name: 'Ellin',
        email: 'LE93@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 69,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Sean',
        last_name: 'Cornell',
        email: 'sec283@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 70,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Travis',
        last_name: 'Judd',
        email: 'ttj22@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 71,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }
    ])
  })
  .then(() => {
    return knex('users').insert([
      {
        team_id: 1,
        first_name: 'Ethan',
        last_name: 'Cramton',
        email: 'egc24@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 72,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Aloja',
        last_name: 'Airewele',
        email: 'aaa247@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 73,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Kenneth',
        last_name: 'McLaurin Jr.',
        email: 'kem228@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 74,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Hector',
        last_name: 'Chang',
        email: 'hdc38@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 75,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Zachary',
        last_name: 'Kozlowski',
        email: 'zak6@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 76,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Marc',
        last_name: 'Barker',
        email: 'mab565@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 77,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Britton',
        last_name: 'Dougherty',
        email: 'bmd88@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 78,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Christopher',
        last_name: 'Kai-Jones',
        email: 'chj7@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 79,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Gibrian',
        last_name: 'Hagood',
        email: 'gah225@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 80,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Hannah',
        last_name: 'Kinsella',
        email: 'hdk29@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 81,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Judy',
        last_name: 'Burrill',
        email: 'judyburrill@gmail.com',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 82,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Khulani',
        last_name: 'Mkhonza',
        email: 'km646@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 83,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Phoebe',
        last_name: 'Brown',
        email: 'peb28@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 84,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Deborah',
        last_name: 'Campos',
        email: 'dc865@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 85,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Nancy Corwin',
        last_name: 'Malina',
        email: 'ncm55@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 86,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Zoë',
        last_name: 'Van Nostrand',
        email: 'ziv2@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 87,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Terry',
        last_name: 'Carroll',
        email: 'tc629@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 88,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Adam',
        last_name: 'Flint',
        email: 'asf87@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 89,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Megan',
        last_name: 'Pulver',
        email: 'msp94@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 90,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Megan',
        last_name: 'Szpak',
        email: 'mjs487@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 91,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Jack',
        last_name: 'Davison',
        email: 'JSD253@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 92,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Eric',
        last_name: 'Carter',
        email: 'EMC333@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 93,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Laura',
        last_name: 'Komor',
        email: 'LRK57@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 94,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Michele L.',
        last_name: 'Jones',
        email: 'mlj77@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 95,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Rebecca',
        last_name: 'Mendèz',
        email: 'rjm442@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 96,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Kina',
        last_name: 'Viola',
        email: 'kv89@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 97,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Thena ',
        last_name: 'LeVan',
        email: 'tlc98@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 98,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Reed',
        last_name: 'Steberger',
        email: 'reed@multiculturalresourcecenter.org',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 99,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Davi',
        last_name: 'Mozie',
        email: 'dm568@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 100,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Rachel',
        last_name: 'Evarts',
        email: 'RDE45@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 101,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Khalil',
        last_name: 'Bey',
        email: 'akb29@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 102,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 1,
        first_name: 'Annalise',
        last_name: 'Kukor',
        email: 'abk95@cornell.edu',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 103,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }, {
        team_id: 2,
        first_name: 'Greg',
        last_name: 'Kops',
        email: 'greg@thinktopography.com',
        password_salt: '$2a$10$wlhVrmkAu7H7Wttks/9vte',
        password_hash: '$2a$10$wlhVrmkAu7H7Wttks/9vte8KTY6afM7XHdKTXadrXlpvpVgfHyx6m',
        photo_id: 106,
        security_question_1_id: 1,
        security_question_1_answer: 'moly',
        security_question_2_id: 2,
        security_question_2_answer: 'zaleski'
      }
    ])
  })
  .then(() => {
    return knex('searches').del()
  })
  .then(() => {
    return knex('searches').insert([
      {
        team_id: 1,
        user_id: 1,
        text: 'Ken Schlather',
        subtext: 'ks47@cornell.edu',
        photo: '/image/ken.jpg',
        route: '/admin/contacts/21'
      }
    ])
  })
  .then(() => {
    return knex('stories').del()
  })
  .then(() => {
    return knex('stories').insert([
      {
        text: 'created {subject}'
      }, {
        text: 'created {subject} in {object1}'
      }
    ])
  })
  .then(() => {
    return knex('activities').del()
  })
  .then(() => {
    return knex('activities').insert([
      {
        team_id: 1,
        user_id: 1,
        story_id: 1,
        app_id: 2,
        url: '/admin/expenses/projects/1',
        subject_type: 'project',
        subject_text: 'Primitive Pursuits',
        created_at: '2016-04-01'
      }, {
        team_id: 1,
        user_id: 1,
        story_id: 2,
        app_id: 2,
        url: '/admin/expenses/expenses',
        subject_type: 'expense',
        subject_text: 'food for party',
        object1_type: 'project',
        object1_text: 'Primitive Pursuits',
        created_at: '2016-04-02'
      }, {
        team_id: 1,
        user_id: 95,
        story_id: 2,
        app_id: 2,
        url: '/admin/expenses/expenses',
        subject_type: 'expense',
        subject_text: 'food for party',
        object1_type: 'project',
        object1_text: 'Primitive Pursuits',
        created_at: '2016-04-02'
      }, {
        team_id: 1,
        user_id: 49,
        story_id: 2,
        app_id: 2,
        url: '/admin/expenses/expenses',
        subject_type: 'expense',
        subject_text: 'food for party',
        object1_type: 'project',
        object1_text: 'Primitive Pursuits',
        created_at: '2016-04-02'
      }, {
        team_id: 1,
        user_id: 54,
        story_id: 1,
        app_id: 2,
        url: '/admin/expenses/projects/2',
        subject_type: 'project',
        subject_text: 'Eat Smart New York',
        created_at: '2016-04-03'
      }, {
        team_id: 1,
        user_id: 19,
        story_id: 1,
        app_id: 2,
        url: '/admin/expenses/projects/3',
        subject_type: 'project',
        subject_text: 'Website Platform',
        created_at: '2016-04-03'
      }, {
        team_id: 1,
        user_id: 13,
        story_id: 2,
        app_id: 2,
        url: '/admin/expenses/expenses',
        subject_type: 'expense',
        subject_text: 'food for party',
        object1_type: 'project',
        object1_text: 'Eat Smart New York',
        created_at: '2016-04-04'
      }, {
        team_id: 1,
        user_id: 13,
        story_id: 2,
        app_id: 2,
        url: '/admin/expenses/expenses',
        subject_type: 'expense',
        subject_text: 'website hosting',
        object1_type: 'project',
        object1_text: 'Eat Smart New York',
        created_at: '2016-04-04'
      }, {
        team_id: 1,
        user_id: 48,
        story_id: 2,
        app_id: 2,
        url: '/admin/expenses/expenses',
        subject_type: 'expense',
        subject_text: 'website hosting',
        object1_type: 'project',
        object1_text: 'Eat Smart New York',
        created_at: '2016-04-05'
      }, {
        team_id: 1,
        user_id: 13,
        story_id: 2,
        app_id: 2,
        url: '/admin/expenses/expenses',
        subject_type: 'expense',
        subject_text: 'website hosting',
        object1_type: 'project',
        object1_text: 'Eat Smart New York',
        created_at: '2016-04-05'
      }, {
        team_id: 1,
        user_id: 21,
        story_id: 1,
        app_id: 2,
        url: '/admin/expenses/projects/3',
        subject_type: 'project',
        subject_text: 'Website Platform',
        created_at: '2016-04-05'
      }, {
        team_id: 1,
        user_id: 21,
        story_id: 1,
        app_id: 2,
        url: '/admin/expenses/projects/3',
        subject_type: 'project',
        subject_text: 'Website Platform',
        created_at: '2016-04-05'
      }, {
        team_id: 1,
        user_id: 49,
        story_id: 2,
        app_id: 2,
        url: '/admin/expenses/expenses',
        subject_type: 'expense',
        subject_text: 'food for party',
        object1_type: 'project',
        object1_text: 'Primitive Pursuits',
        created_at: '2016-04-06'
      }, {
        team_id: 1,
        user_id: 64,
        story_id: 2,
        app_id: 2,
        url: '/admin/expenses/expenses',
        subject_type: 'expense',
        subject_text: 'food for party',
        object1_type: 'project',
        object1_text: 'Primitive Pursuits',
        created_at: '2016-04-07'
      }, {
        team_id: 1,
        user_id: 49,
        story_id: 2,
        app_id: 2,
        url: '/admin/expenses/expenses',
        subject_type: 'expense',
        subject_text: 'food for party',
        object1_type: 'project',
        object1_text: 'Primitive Pursuits',
        created_at: '2016-04-08'
      }
    ])
  })
  .then(() => {
    return knex('roles').del()
  })
  .then(() => {
    return knex('roles').insert([
      {
        team_id: 1,
        title: 'Administrator',
        description: 'Sriracha bitters fixie bicycle rights, shoreditch lomo retro snackwave cold-pressed bespoke banjo synth beard keytar. '
      }, {
        team_id: 1,
        title: 'Supervisor',
        description: 'Sriracha bitters fixie bicycle rights, shoreditch lomo retro snackwave cold-pressed bespoke banjo synth beard keytar. '
      }, {
        team_id: 1,
        title: 'Finance',
        description: 'Sriracha bitters fixie bicycle rights, shoreditch lomo retro snackwave cold-pressed bespoke banjo synth beard keytar. '
      }, {
        team_id: 1,
        title: 'Employee',
        description: 'Sriracha bitters fixie bicycle rights, shoreditch lomo retro snackwave cold-pressed bespoke banjo synth beard keytar. '
      }
    ])
  })  .then(() => {
    return knex('roles_apps').del()
  })
  .then(() => {
    return knex('roles_apps').insert([
      {
        role_id: 1,
        app_id: 1
      }, {
        role_id: 1,
        app_id: 2
      }, {
        role_id: 1,
        app_id: 3
      }, {
        role_id: 1,
        app_id: 4
      }, {
        role_id: 1,
        app_id: 5
      }
    ])
  })
  .then(() => {
    return knex('roles_rights').del()
  })
  .then(() => {
    return knex('roles_rights').insert([
      {
        role_id: 1,
        right_id: 1
      }, {
        role_id: 1,
        right_id: 2
      }, {
        role_id: 1,
        right_id: 3
      }, {
        role_id: 1,
        right_id: 4
      }
    ])
  })
  .then(() => {
    return knex('users_roles').del()
  })
  .then(() => {
    return knex('users_roles').insert([
      {
        user_id: 1,
        role_id: 1
      }, {
        user_id: 1,
        role_id: 4
      }, {
        user_id: 2,
        role_id: 1
      }, {
        user_id: 2,
        role_id: 4
      }, {
        user_id: 3,
        role_id: 4
      }, {
        user_id: 4,
        role_id: 4
      }, {
        user_id: 5,
        role_id: 4
      }, {
        user_id: 6,
        role_id: 4
      }, {
        user_id: 7,
        role_id: 4
      }, {
        user_id: 8,
        role_id: 4
      }, {
        user_id: 9,
        role_id: 1
      }, {
        user_id: 9,
        role_id: 4
      }, {
        user_id: 11,
        role_id: 3
      }, {
        user_id: 11,
        role_id: 4
      }, {
        user_id: 20,
        role_id: 2
      }, {
        user_id: 20,
        role_id: 4
      }, {
        user_id: 21,
        role_id: 1
      }, {
        user_id: 21,
        role_id: 4
      }, {
        user_id: 23,
        role_id: 2
      }, {
        user_id: 23,
        role_id: 4
      }, {
        user_id: 45,
        role_id: 1
      }, {
        user_id: 45,
        role_id: 4
      }, {
        user_id: 47,
        role_id: 3
      }, {
        user_id: 47,
        role_id: 4
      }, {
        user_id: 80,
        role_id: 3
      }, {
        user_id: 80,
        role_id: 4
      }
    ])
  })
}
