// @flow

export const LOAD_PREFERENCES_REQUEST: string = 'browser/LOAD_PREFERENCES_REQUEST'
export const LOAD_PREFERENCES_SUCCESS: string = 'browser/LOAD_PREFERENCES_SUCCESS'
export const LOAD_PREFERENCES_FAILURE: string = 'browser/LOAD_PREFERENCES_FAILURE'

export const SAVE_PREFERENCES_REQUEST: string = 'browser/SAVE_PREFERENCES_REQUEST'
export const SAVE_PREFERENCES_SUCCESS: string = 'browser/SAVE_PREFERENCES_SUCCESS'
export const SAVE_PREFERENCES_FAILURE: string = 'browser/SAVE_PREFERENCES_FAILURE'

export const SET_PREFERENCE: string = 'browser/SET_PREFERENCE'
