const reserved = [
  'action',
  'afterCommit',
  'afterProcessor',
  'allowedParams',
  'alterRecord',
  'alterRequest',
  'beforeCommit',
  'beforeProcessor',
  'beforeRollback',
  'collectionActions',
  'defaultFormat',
  'defaultLimit',
  'except',
  'filterParams',
  'knex',
  'logger',
  'memberActions',
  'method',
  'model',
  'only',
  'path',
  'plugins',
  'processor',
  'resourceOptions',
  'routes',
  'serializer',
  'sortParams'
]

export default reserved
