// @flow

export const LOAD_REQUEST: string = 'filter/LOAD_REQUEST'
export const LOAD_SUCCESS: string = 'filter/LOAD_SUCCESS'
export const LOAD_FAILURE: string = 'filter/LOAD_FAILURE'
export const SET: string = 'filter/SET'
export const BACK: string = 'filter/BACK'
export const CHOOSE: string = 'filter/CHOOSE'
export const RESET_ALL: string = 'filter/RESET_ALL'
export const RESET: string = 'filter/RESET'
export const RESTART: string = 'filter/RESTART'
export const UPDATE: string = 'filter/UPDATE'
export const REMOVE: string = 'filter/REMOVE'
export const LOOKUP: string = 'filter/LOOKUP'
export const ABORT: string = 'filter/ABORT'
