// @flow

export const LOAD_REQUEST: string = 'admin.filter/LOAD_REQUEST'
export const LOAD_SUCCESS: string = 'admin.filter/LOAD_SUCCESS'
export const LOAD_FAILURE: string = 'admin.filter/LOAD_FAILURE'
export const SET: string = 'admin.filter/SET'
export const BACK: string = 'admin.filter/BACK'
export const CHOOSE: string = 'admin.filter/CHOOSE'
export const RESET_ALL: string = 'admin.filter/RESET_ALL'
export const RESET: string = 'admin.filter/RESET'
export const RESTART: string = 'admin.filter/RESTART'
export const UPDATE: string = 'admin.filter/UPDATE'
export const REMOVE: string = 'admin.filter/REMOVE'
export const LOOKUP: string = 'admin.filter/LOOKUP'
export const ABORT: string = 'admin.filter/ABORT'
